# Only used for api testing
version: '2'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./.data:/data/db

  api:
    build: .
    depends_on:
      - 'mongodb'
    environment:
      - DB_HOST=localhost
      - DB_PORT=27017
