# Only used for api testing
version: '2'
services:
  mongodb:
    image: mongo
    volumes:
      - ./.data:/data/db

  api:
    build: .
    ports:
      - '8080:8080'
    links:
      - 'mongodb'
    depends_on:
      - 'mongodb'
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - API_PORT=8080
      - API_PATH=/
      - WAIT_HOSTS=mongodb:27017
