# Only used for api testing
# Starts the mongo db container only
# `$ docker-compose -f mongo_only.yml up`
version: '2'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./.data:/data/db
