controller_frequency: 20.0

TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.02
  max_vel_theta: 1.5
  min_vel_theta: -1.5
  min_in_place_vel_theta: 0.05

  acc_lim_theta: 1.5
  acc_lim_x: 0.3

  pdist_scale: 0.8
  occdist_scale: 0.01

  holonomic_robot: false

  xy_goal_tolerance: 0.3
