global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 1.0
  static_map: true
  track_unknown_space: true

  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    obstacle_range: 10.0
