controller_frequency: 10.0
planner_frequency: 1.0

TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.02
  max_vel_theta: 2.0
  min_vel_theta: -2.0
  min_in_place_vel_theta: 0.05

  acc_lim_theta: 3.0
  acc_lim_x: 0.8

  pdist_scale: 3.0
  gdist_scale: 5.0
  occdist_scale: 0.006

  holonomic_robot: false

  xy_goal_tolerance: 0.3

NavfnROS:
  allow_unknown: false
