robot_radius: 0.3
inflation_radius: 2.0
transform_tolerance: 1

laser_scan_sensor:
  sensor_frame: laser
  data_type: LaserScan
  topic: /scan
  marking: true
  clearing: true
  min_obstacle_height: -9.0
  max_obstacle_height: 9.0
  obstacle_range: 10.0
  raytrace_range: 25.0

point_cloud_sensor:
  sensor_frame: camera_link
  data_type: PointCloud2
  topic: /obstacles
  marking: true
  clearing: true
  min_obstacle_height: -9.0
  max_obstacle_height: 2.0
  obstacle_range: 2.0
  raytrace_range: 10.0
