

obstacle_range: 20.0
raytrace_range: 8.0
robot_radius: 0.3
inflation_radius: 0.4
transform_tolerance: 1

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
point_cloud_sensor: {sensor_frame: camera_link, data_type: PointCloud2, topic: /obstacles, marking: true, clearing: true, min_obstacle_height: -9999.9, max_obstacle_height: 2.0}
